/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "ParameterBus.h"

//==============================================================================
BeepBoxAudioProcessorEditor::BeepBoxAudioProcessorEditor (BeepBoxAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
	bus = (ParameterBus*)ownerFilter;

    // This is where our plugin's editor size is set.
    setSize (800, 600);
}

BeepBoxAudioProcessorEditor::~BeepBoxAudioProcessorEditor()
{
}

//==============================================================================
void BeepBoxAudioProcessorEditor::onParameterUpdated(Parameter *parameter)
{
}

//==============================================================================
void BeepBoxAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!",
                      0, 0, getWidth(), getHeight(),
                      Justification::centred, 1);
}
